services:
  app:
    build: .
    ports:
      - "4054:8080"
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qotd
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
